// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    // Supabase auth is deprecated in this repo (migrated to local backend JWT).
    // Keep the client only to avoid breaking legacy imports, but do NOT keep
    // background refresh timers running.
    persistSession: false,
    autoRefreshToken: false,
    detectSessionInUrl: false,
  }
});